# Generated by Django 5.1.4 on 2025-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_bron_user_alter_stadium_manager_and_more"),
        ("user", "0002_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
