# Generated by Django 5.1.4 on 2025-04-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("user", "0002_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bron",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bron_user",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stadium_manager",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="stadium",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stadium_owner",
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="team_members", to="user.user"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
